
services:
  db:
    image: postgis/postgis:latest
    container_name: postgis
    restart: always
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  geoserver:
    image: kartoza/geoserver
    container_name: geoserver
    restart: always
    depends_on:
      - db
    environment:
      GEOSERVER_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  postgis_data:
